# Generated by Django 3.0.3 on 2020-02-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tablero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('fk_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Lista')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='fk_tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Tablero'),
        ),
    ]
